### ISSUE TITLE
pin conflict

### ISSUE THREAD

**Issue by mayday00** [petrockblog/PowerBlock#13]
while trying to setup my system. and found myself in a restart loop. i discovered that the powerblock and the hifiberry dac+ pro share GPIO pin 18. as soon as i unpluged the dac hat. the restart loop was gone. 

i hope this is the right place to put this. im sorry if it isnt

**Comment by CommanderCaveman** [comment]
This is something I noticed yesterday about the potential conflict. It was only reading up today in https://www.raspberrypi.org/app/uploads/2012/02/BCM2835-ARM-Peripherals.pdf#page=119 that I realised that it might not be straight forward, pin 12 GP18 has a secondary function PCM CLK which I suspect the dac relies upon as its part of the audio functionaility of the processor. The quesition is whether the powerblocker relies on a different software configuration of the PCM CLK or if the powerblocker can be configured to use an alternative pin in software and hardware by not plugging directly into the PI header and using floating wires to attach to the PI header.

**Comment by CommanderCaveman** [comment]
Ok so I believe you can with jump wires wire to an alternative pin to pin 12 / GP18, depending on what installation you used directs you to an alternative configuration in software. You would need to adjust the files once they are on your PI at the locations indicated within the relevant instalation file either install.sh or install_libreelec.sh.

For a LibreELEC install you need to configure file  PowerBlock/scripts/libreelec/powerblock.sh and change the GP reference on line 7 to the pin you have chosen.
For the bash only implementation you need to configure the file  PowerBlock/supplementary/powerblockconfig.cfg  and change the GP reference on line 4.

Pls let me know how it goes.

**Comment by petrockblog** [comment]
Sounds like the way to go.
