### ISSUE TITLE
Pins not as configured

### ISSUE THREAD

**Issue by mattbrailsford** [petrockblog/PowerBlock#14]
I’m trying to change the pins used for status + shutdown as I need one of them for i2s audio output. 

I’ve cut the traces for S1 and S2 on the underside of the board next to the header and have changes the config file to use pins 6 and 12, however when I check my log file the powerblockservice reports the pins as 31 and 32 and the pins don’t seem to work. The led just remains slow flashing and toggling the button doesn’t shut down. 

I can’t understand why it’s outputting different pin values than configured 🤔

**Comment by alwinbakema** [comment]
Hi @mattbrailsford Did you solve this issue? I have the same issue. 
I can power on my device with the power button.
But when i want to shutdown the led keeps slowly blinking. And unable to power down the device.

**Comment by petrockblog** [comment]
@alwinbakema 
> Hi @mattbrailsford Did you solve this issue? I have the same issue. I can power on my device with the power button. But when i want to shutdown the led keeps slowly blinking. And unable to power down the device.

I suspect that you are observing issues due to the transition to the new GPIO interface. We address this in at https://github.com/petrockblog/PowerBlock/issues/15. Hope that helps? Let's continue the discussion at https://github.com/petrockblog/PowerBlock/issues/15.
