### ISSUE TITLE
Error during instalation

### ISSUE THREAD

**Issue by Martin-Noel** [petrockblog/PowerBlock#7]
Hi,

Trying to install the driver on Retropie  4.9.35-v7 / Raspberry Pi 3, i have this error at the 63% step :: 

[ 63%] Building CXX object CMakeFiles/powerblock.dir/src/powerblock/main.cpp.o
/root/PowerBlock/src/powerblock/main.cpp:30:17: error: ‘sig_atomic_t’ does not name a type
 static volatile sig_atomic_t doRun = 1;
                 ^
/root/PowerBlock/src/powerblock/main.cpp: In function ‘void sig_handler(int)’:
/root/PowerBlock/src/powerblock/main.cpp:35:19: error: ‘SIGINT’ was not declared in this scope
     if ((signo == SIGINT) | (signo == SIGQUIT) | (signo == SIGABRT) | (signo == SIGTERM))
                   ^
/root/PowerBlock/src/powerblock/main.cpp:35:39: error: ‘SIGQUIT’ was not declared in this scope
     if ((signo == SIGINT) | (signo == SIGQUIT) | (signo == SIGABRT) | (signo == SIGTERM))
                                       ^
/root/PowerBlock/src/powerblock/main.cpp:35:60: error: ‘SIGABRT’ was not declared in this scope
     if ((signo == SIGINT) | (signo == SIGQUIT) | (signo == SIGABRT) | (signo == SIGTERM))
                                                            ^
/root/PowerBlock/src/powerblock/main.cpp:35:81: error: ‘SIGTERM’ was not declared in this scope
     if ((signo == SIGINT) | (signo == SIGQUIT) | (signo == SIGABRT) | (signo == SIGTERM))
                                                                                 ^
/root/PowerBlock/src/powerblock/main.cpp:38:9: error: ‘doRun’ was not declared in this scope
         doRun = 0;
         ^
/root/PowerBlock/src/powerblock/main.cpp: In function ‘void register_signalhandlers()’:
/root/PowerBlock/src/powerblock/main.cpp:46:16: error: ‘SIGINT’ was not declared in this scope
     if (signal(SIGINT, sig_handler) == SIG_ERR)
                ^
/root/PowerBlock/src/powerblock/main.cpp:46:35: error: ‘signal’ was not declared in this scope
     if (signal(SIGINT, sig_handler) == SIG_ERR)
                                   ^
/root/PowerBlock/src/powerblock/main.cpp:46:40: error: ‘SIG_ERR’ was not declared in this scope
     if (signal(SIGINT, sig_handler) == SIG_ERR)
                                        ^
/root/PowerBlock/src/powerblock/main.cpp:50:16: error: ‘SIGQUIT’ was not declared in this scope
     if (signal(SIGQUIT, sig_handler) == SIG_ERR)
                ^
/root/PowerBlock/src/powerblock/main.cpp:50:36: error: ‘signal’ was not declared in this scope
     if (signal(SIGQUIT, sig_handler) == SIG_ERR)
                                    ^
/root/PowerBlock/src/powerblock/main.cpp:50:41: error: ‘SIG_ERR’ was not declared in this scope
     if (signal(SIGQUIT, sig_handler) == SIG_ERR)
                                         ^
/root/PowerBlock/src/powerblock/main.cpp:54:16: error: ‘SIGABRT’ was not declared in this scope
     if (signal(SIGABRT, sig_handler) == SIG_ERR)
                ^
/root/PowerBlock/src/powerblock/main.cpp:54:36: error: ‘signal’ was not declared in this scope
     if (signal(SIGABRT, sig_handler) == SIG_ERR)
                                    ^
/root/PowerBlock/src/powerblock/main.cpp:54:41: error: ‘SIG_ERR’ was not declared in this scope
     if (signal(SIGABRT, sig_handler) == SIG_ERR)
                                         ^
/root/PowerBlock/src/powerblock/main.cpp:58:16: error: ‘SIGTERM’ was not declared in this scope
     if (signal(SIGTERM, sig_handler) == SIG_ERR)
                ^
/root/PowerBlock/src/powerblock/main.cpp:58:36: error: ‘signal’ was not declared in this scope
     if (signal(SIGTERM, sig_handler) == SIG_ERR)
                                    ^
/root/PowerBlock/src/powerblock/main.cpp:58:41: error: ‘SIG_ERR’ was not declared in this scope
     if (signal(SIGTERM, sig_handler) == SIG_ERR)
                                         ^
/root/PowerBlock/src/powerblock/main.cpp: In function ‘int main(int, char**)’:
/root/PowerBlock/src/powerblock/main.cpp:69:12: error: ‘doRun’ was not declared in this scope
     while (doRun)
            ^
CMakeFiles/powerblock.dir/build.make:62: recipe for target 'CMakeFiles/powerblock.dir/src/powerblock/main.cpp.o' failed
make[2]: *** [CMakeFiles/powerblock.dir/src/powerblock/main.cpp.o] Error 1
CMakeFiles/Makefile2:165: recipe for target 'CMakeFiles/powerblock.dir/all' failed
make[1]: *** [CMakeFiles/powerblock.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
Error during installation of binary
Scanning dependencies of target installservice
[100%] Installing service.
[100%] Built target installservice
~/PowerBlock
[ERROR] The PowerBlock driver binary is not installed
[ERROR] The PowerBlock service is not running

Do you have any advice for this ?

Thanks

**Comment by petrockblog** [comment]
That is fixed with the recent commit.
